sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sohel2109/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sohel2109/client-test npm test

after_success:
  - docker build -t sohel2109/client ./client
  - docker build -t sohel2109/api ./server
  - docker build -t sohel2109/nginx ./nginx
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push sohel2109/client
  - docker push sohel2109/api
  - docker push sohel2109/nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker-todo
  env: MultiDockerTodo-env-1
  bucket_name: elasticbeanstalk-ap-northeast-1-560168190547
  bucket_path: multi-docker-todo
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
